#!/bin/bash

source /etc/os-release

curPath=`readlink -f $0`
curDir=`dirname $curPath`

echo "DIR: $curDir"

if [ $ID == "debian" ] && [ $VERSION_ID -lt 13 ]
then
	echo "OS version is debian lower 13.x. Will change to the gpiod1.x branch"
	if [ `git branch --list | tr '\n' '#' | grep -cE "[[:space:]]gpiod1\.x#"` -gt 0 ]
	then
		echo "Changing to existing branch gpiod1.x"	
		git checkout gpiod1.x
	else
		echo "Checking out branch gpiod1.x from remote"
		git checkout --track origin/gpiod1.x
	fi
else
	echo "OS version is either no debian or debian but newer/equal 13.x. Will keep the current branch"
fi

echo -n "Check for package libgpiod-dev and install if needed..."
if [ `apt list --installed libgpiod-dev 2>/dev/null | grep -c libgpiod-dev` -lt 1 ]
then
	echo "missing"
	echo "Installing missing package libgpiod-dev..."
	sudo apt -y update && sudo apt -y install libgpiod-dev
	if [ $? -gt 0 ]
	then
		echo "failed"
		exit 1
	else
		echo "done"
	fi
else
	echo "Skipping. Already installed."
fi

echo -n "Check for package gpiod and install if needed..."
if [ `apt list --installed gpiod 2>/dev/null | grep -c gpiod` -lt 1 ]
then
        echo "missing"
        echo "Installing missing package gpiod..."
        sudo apt -y update && sudo apt -y install gpiod
        if [ $? -gt 0 ]
        then
                echo "failed"
                exit 1
        else
                echo "done"
        fi
else
        echo "Skipping. Already installed."
fi

echo "Calling converter script to gather info about the gpio chips, lines and names..."

/bin/env 1>/dev/null 2>/dev/null
if [ $? -gt 0 ]
then
	python3 ./convertGpioInfo2Json.py
else
	./convertGpioInfo2Json.py
fi

if [ $? -gt 0 ]
then
	echo "Failed to convert info of gpioinfo command. Aborting"
	exit 1
else
	echo "Got the info we need and got it converted."
fi
